### ISSUE TITLE
bad gush IDs on the Herzliya map

### ISSUE THREAD

**Issue by niryariv** [niryariv/opentaba-client#106]
seems like something went wrong during scraping, eg, gush with ID "0": 
![screen shot 2014-12-30 at 4 40 50 pm](https://cloud.githubusercontent.com/assets/1771/5579400/ab2f3672-9042-11e4-9266-b595a5619c54.png)

https://github.com/niryariv/israel_gushim/blob/master/herzliya.topojson

**Comment by florpor** [comment]
fixed: https://github.com/niryariv/israel_gushim/commit/5c5c2c49757673d20c5dd3cf2fdb98be48678763
