### ISSUE TITLE
top right icons look weird when facebook and/or twitter feeds are missing

### ISSUE THREAD

**Issue by florpor** [niryariv/opentaba-client#114]
there's an empty space between the new icons (notifier and forum) and the rss feed one

![screenshot from 2016-06-13 17-54-33](https://cloud.githubusercontent.com/assets/1809093/16011988/307bee20-3190-11e6-9946-9a41ded2cc9a.png)

**Comment by niryariv** [comment]
@noamoss ^

**Comment by noamoss** [comment]
https://github.com/niryariv/opentaba-client/pull/115

**Comment by noamoss** [comment]
fixed on https://github.com/niryariv/opentaba-client/commit/3a2b06c4467f00035d80340473ec5699ee01bd0b

**Comment by niryariv** [comment]
@noamoss awesome! pushed to live.

(btw plz assign to me before closing, we only close once the fix is deployed on the live site :)
